/** Record the real sample workflow. No live provider requests; no customer data.
 * Start the app first, then: node scripts/record-demo.mjs
 * Requires @playwright/test Chromium and ffmpeg. Output is silent, ready for Shivam's narration.
 */
import { chromium, expect } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
const root=process.cwd(),base=process.env.REMAINDER_DEMO_URL||'http://localhost:3210';
const raw=path.join(root,'.artifacts/video'),media=path.join(root,'public/media'),out=path.join(root,'deliverables');
await Promise.all([fs.mkdir(raw,{recursive:true}),fs.mkdir(media,{recursive:true}),fs.mkdir(out,{recursive:true})]);
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1600,height:900},recordVideo:{dir:raw,size:{width:1600,height:900}},acceptDownloads:true,reducedMotion:'reduce'});
const page=await context.newPage();const video=page.video();const marks=[];const errors=[];page.on('pageerror',e=>errors.push(e.message));
const start=Date.now();
async function at(second,name,fn){const delay=second*1000-(Date.now()-start);if(delay>0)await page.waitForTimeout(delay);marks.push({second:Number(((Date.now()-start)/1000).toFixed(2)),name});console.log(name);if(fn)await fn();}
async function hideCard(){await page.evaluate(()=>document.querySelector('#recording-card')?.remove());}
async function caption(label,text){await page.evaluate(({label,text})=>{let d=document.querySelector('#recording-caption');if(!d){d=document.createElement('div');d.id='recording-caption';document.body.append(d);}Object.assign(d.style,{position:'fixed',zIndex:'99990',left:'258px',right:'34px',bottom:'18px',padding:'14px 20px',border:'1px solid #cbd8c8',borderRadius:'9px',background:'rgba(247,250,245,.97)',boxShadow:'0 5px 24px #163b2020',fontFamily:'Arial,sans-serif',color:'#194d3b',pointerEvents:'none'});d.replaceChildren();const l=document.createElement('div');l.textContent=label;Object.assign(l.style,{fontSize:'10px',fontWeight:'700',letterSpacing:'1.5px',marginBottom:'5px'});const p=document.createElement('div');p.textContent=text;Object.assign(p.style,{fontSize:'17px',lineHeight:'1.35'});d.append(l,p);},{label,text});}
async function card(label,title,body,small){await page.evaluate(({label,title,body,small})=>{document.querySelector('#recording-caption')?.remove();document.querySelector('#recording-card')?.remove();const d=document.createElement('div');d.id='recording-card';Object.assign(d.style,{position:'fixed',inset:'0',zIndex:'99999',background:'#f7f8f5',color:'#194d3b',fontFamily:'Arial,sans-serif',padding:'104px 140px',display:'flex',flexDirection:'column',justifyContent:'center'});for(const [text,style] of [[label,{fontSize:'14px',letterSpacing:'3px',fontWeight:'700',marginBottom:'26px',textTransform:'uppercase'}],[title,{fontFamily:'Georgia,serif',fontSize:'70px',lineHeight:'1.06',maxWidth:'1100px',whiteSpace:'pre-line'}],[body,{fontSize:'28px',lineHeight:'1.45',color:'#4e6555',maxWidth:'1100px',marginTop:'34px',whiteSpace:'pre-line'}],[small,{fontSize:'15px',lineHeight:'1.6',color:'#6b7b6b',marginTop:'42px',maxWidth:'1050px'}]]){const p=document.createElement('div');p.textContent=text;Object.assign(p.style,style);d.append(p);}document.body.append(d);},{label,title,body,small});}
async function shot(name,fullPage=false){await page.screenshot({path:path.join(media,name),fullPage});}
try{
 await page.goto(base);await page.waitForLoadState('networkidle');
 await shot('landing-desktop.png');
 await card('Remainder · a fictional product walkthrough','“We’ll credit you.”\nBut how much?','A supplier-credit desk for independent food businesses.','Created by Shivam Gupta with AI-assisted engineering. Silent walkthrough; narration supplied separately.');
 await at(8,'landing',async()=>{await hideCard();await caption('THE PROBLEM','A partial credit can make an unfinished claim look complete.');});
 await at(16,'demo entry',async()=>{await page.getByRole('button',{name:'Explore the sample demo'}).click();await page.waitForURL('**/app');await page.evaluate(()=>document.querySelector('#recording-caption')?.remove());await shot('dashboard-desktop.png');await caption('FICTIONAL SAMPLE · ISOLATED WORKSPACE','This is a working sample replay. No live AI request is made in this recording.');});
 await at(25,'open case',async()=>{await page.getByRole('link',{name:'A delivery that came up short'}).first().click();await expect(page.getByRole('checkbox',{name:'Include in claim'})).toHaveCount(2);await caption('01 / COLLECT THE EVIDENCE','Invoice NF-1042 and its receiving record, together in one case.');await page.evaluate(()=>window.scrollTo(0,0));});
 const caseUrl=page.url();
 await at(32,'invoice evidence',async()=>{await page.getByRole('button',{name:'Invoice',exact:true}).first().click();await expect(page.getByRole('dialog')).toContainText('Unit price: USD 36.00');await caption('THE INVOICE','12 oat-drink cases at $36 each. 10 tomato cases at $24 each.');});
 await at(42,'receiving evidence',async()=>{await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'Delivery note',exact:true}).first().click();await caption('THE RECEIVING RECORD','8 oat-drink cases received. 7 tomato cases received.');});
 await at(51,'shortage findings',async()=>{await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('checkbox',{name:'Include in claim'}).first().scrollIntoViewIfNeeded();await caption('02 / REVIEW THE SHORTAGES','$144 for oat drink + $72 for tomatoes = $216 to review.');});
 await at(60,'accept findings',async()=>{for(let i=0;i<2;i++){const box=page.getByRole('checkbox',{name:'Include in claim'}).nth(i);await box.click();await expect(box).toBeChecked();await expect(box).toBeEnabled();await page.waitForTimeout(800);}await caption('EXPLICIT REVIEW','Source-backed findings start unchecked. The owner decides what enters the claim.');});
 await at(69,'prepare claim',async()=>{await page.getByRole('button',{name:'Prepare claim',exact:true}).click();await caption('03 / PREPARE A REVIEWED CLAIM','Confirm the evidence before preparing the $216 supplier request.');});
 await at(75,'approve and open draft',async()=>{await page.getByRole('button',{name:'I reviewed it. Prepare claim.'}).click();await expect(page.getByText('Claim prepared',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Claim draft'}).click();await caption('READY FOR THE OWNER TO SEND','A supplier email draft and evidence PDF. Remainder does not send messages.');});
 await at(83,'download evidence',async()=>{const wait=page.waitForEvent('download');await page.getByRole('link',{name:'Evidence PDF',exact:true}).click();await(await wait).saveAs(path.join(out,'sample-claim-evidence.pdf'));await page.waitForTimeout(500);await page.getByRole('link',{name:'Email draft',exact:true}).click();});
 await at(92,'credit arrives',async()=>{await page.getByRole('button',{name:'Add credit note',exact:true}).click();await page.getByRole('button',{name:'Load the $144 sample credit note'}).click();await caption('04 / A CREDIT ARRIVES','CN-208 references NF-1042 and covers only $144 of the original $216 claim.');});
 await at(101,'match credit',async()=>{await page.getByRole('button',{name:'Save reviewed text'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('tab',{name:'Findings'}).click();await page.getByRole('button',{name:'Match new credit'}).click();await expect(page.getByRole('button',{name:'Verify credit',exact:true})).toBeVisible();await page.getByRole('button',{name:'Inspect evidence',exact:true}).click();await caption('REVIEW THE CREDIT NOTE','Correct supplier. Correct invoice. Exact credit amount and quoted source.');});
 await at(111,'verify partial credit',async()=>{await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'Verify credit',exact:true}).click();await expect(page.getByText('Partially credited',{exact:true})).toBeVisible();await page.evaluate(()=>window.scrollTo(0,0));await caption('05 / KEEP THE REMAINDER OPEN','$216 claimed · $144 verified in credit notes · $72 still outstanding.');});
 await at(119,'balance screenshot',async()=>{await page.evaluate(()=>document.querySelector('#recording-caption')?.remove());await shot('case-desktop.png');await shot('case-full.png',true);await caption('CREDIT NOTES ARE NOT CASH','Applying a credit to a bill or receiving cash remains a separate accounting step.');});
 await at(128,'provenance',async()=>{await page.getByText('Sample replay',{exact:true}).first().scrollIntoViewIfNeeded();await caption('THE AI BOUNDARY','This recording uses labeled replay. The live adapter checks structured output against source evidence.');});
 await at(136,'supplier context',async()=>{await page.goto(base+'/app/suppliers');await page.waitForLoadState('networkidle');await caption('WORKSPACE MEMORY','Confirmed supplier aliases stay in this workspace. Money and duplicate checks stay in code.');});
 await at(144,'commercial plan',async()=>{await card('Go-to-market · hypotheses to validate','Start with one real case.','Independent cafes + hospitality bookkeepers\nMeasure review time, corrections and repeat use.\nThen ask for a paid commitment.','Pre-launch. No external users, supplier recoveries, revenue or partnerships are claimed.');});
 await at(153,'pricing hypothesis',async()=>{await card('Pricing hypothesis','$29 / location / month','Up to 100 claim packs, subject to a defined analysis allowance.\nValidate inference costs and support time before scaling.','Evorozen advertises the first 50 calls free: a finite launch allowance. This is proposed pricing, not an active subscription offer.');});
 await at(162,'closing frame',async()=>{await card('Created by Shivam Gupta','Remainder.','Know exactly what is still outstanding.','$216 reviewed claim · $144 verified credit note · $72 remains open. Fictional sample; credit-note verification is not proof of cash received.');});
 await at(170,'end');
 const final=await(await context.request.get(base+`/api/cases/${caseUrl.split('/').pop()}`)).json();
 if(final.case.claimedCents!==21600||final.case.creditedCents!==14400||final.case.remainingCents!==7200)throw new Error('Final balance verification failed');
 await hideCard();await page.goto(caseUrl);await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);await page.screenshot({path:path.join(media,'case-mobile.png'),fullPage:true});
}catch(e){console.error(e);process.exitCode=1;await page.screenshot({path:path.join(raw,'failure.png'),fullPage:true});}
finally{await context.close();const source=await video.path();await fs.writeFile(path.join(raw,'recording.json'),JSON.stringify({marks,errors,source,recording:'fictional sample replay; no live AI request'},null,2));await browser.close();if(!process.exitCode){const proof=path.join(raw,'live-proof.png');const hasProof=await fs.access(proof).then(()=>true).catch(()=>false);const filters=hasProof?['-i',proof,'-filter_complex',"[0:v]scale=1920:1080:flags=lanczos[base];[base][1:v]overlay=0:0:enable='between(t,128,144)':eof_action=repeat[v]",'-map','[v]']:['-vf','scale=1920:1080:flags=lanczos'];execFileSync('ffmpeg',['-hide_banner','-loglevel','error','-y','-i',source,...filters,'-t','170','-c:v','libx264','-preset','medium','-crf','20','-pix_fmt','yuv420p','-an','-movflags','+faststart',path.join(out,'remainder-walkthrough-silent.mp4')],{stdio:'inherit'});console.log('Saved deliverables/remainder-walkthrough-silent.mp4');}}
