import { Link } from 'react-router-dom';
import { ArrowDown, ArrowRight, Check, CheckCheck, CircleCheck, FileText, Leaf, Link2, MoveUpRight, ReceiptText, ShieldCheck, Sparkles } from 'lucide-react';
import { Logo } from './ui';

export function Landing({ onDemo, busy }: { onDemo: () => void; busy: boolean }) {
  return <div className="landing"><header className="landing-nav"><Logo/><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#why-remainder">Why Remainder</a><a href="#pricing">Pricing</a></nav><div className="nav-actions"><Link to="/login" className="login-link">Log in</Link><Link to="/signup" className="button">Start your workspace <ArrowRight size={16}/></Link></div></header>
    <main><section className="hero"><div className="hero-copy"><div className="hero-kicker"><span/><span>A little less admin. A lot more accounted for.</span></div><h1>“We’ll credit you.”<br/><span>Let’s make sure<br className="desktop-break"/> they do.</span></h1><p>Short deliveries. Missing credits. Endless follow-ups.<br className="desktop-break"/> Remainder connects the paperwork, prepares your claim,<br className="desktop-break"/> and keeps every supplier credit in sight.</p><div className="hero-actions"><button className="button button-large" onClick={onDemo} disabled={busy}>{busy ? 'Opening your workspace…' : 'Explore the sample demo'}<ArrowRight size={18}/></button><a href="#how-it-works" className="button button-ghost">See how it works <ArrowDown size={16}/></a></div><div className="hero-meta"><Check size={14}/> No card. No accounting integration. Just your documents.</div></div>
    <div className="hero-visual" aria-label="Illustrative recovery: $216 claimed, $144 credit verified, $72 still outstanding"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="little-cross cross-one">+</div><div className="little-cross cross-two">+</div><div className="receipt-card"><div className="receipt-head"><div className="supplier-symbol"><Leaf size={22}/></div><div><b>Northstar Foods</b><span>INVOICE NF-1042</span></div><span className="receipt-date">SEP 23</span></div><div className="receipt-rule"/><div className="receipt-row"><span>Barista oat milk</span><span>12 cases</span><b>$432.00</b></div><div className="receipt-row"><span>Whole tomatoes</span><span>10 cases</span><b>$240.00</b></div><div className="receipt-row"><span>Extra virgin olive oil</span><span>4 tins</span><b>$128.00</b></div><div className="receipt-note"><CircleCheck size={16}/><span>Matched to your delivery note</span></div><div className="receipt-total"><span>Short delivery identified</span><b>$216.00</b></div><div className="receipt-tear"/></div><div className="floating-tag tag-evidence"><span><Link2 size={15}/></span>Every finding has a source</div><div className="credit-card"><div className="credit-top"><span className="credit-icon"><CheckCheck size={21}/></span><span>Credit note verified<b>CN-208 · Northstar Foods</b></span><b>$144.00</b></div><div className="credit-progress"><i/></div><div className="credit-bottom"><span>One part resolved.</span><strong>$72.00 still open <ArrowRight size={14}/></strong></div></div><div className="visual-caption">ILLUSTRATIVE CASE · REAL WORKFLOW</div></div>
    </section><section className="trust-strip"><span>Made for the people<br/><b>behind the counter.</b></span><div><Leaf size={20}/> Independent cafés</div><div><ReceiptText size={20}/> Restaurants & kitchens</div><div><FileText size={20}/> Food retailers</div><div className="powered"><Sparkles size={17}/> Built for Evorozen Apex</div></section>
    <section id="how-it-works" className="how-section"><div className="section-intro"><div className="eyebrow">FROM PAPERWORK TO PEACE OF MIND</div><h2>The invoice is only<br/><em>half the story.</em></h2><p>When what you paid for isn’t what arrived,<br/>follow the difference all the way through.</p></div><div className="steps"><article><div className="step-number">01 <FileText size={21}/></div><h3>Bring the paper trail.</h3><p>Add an invoice, a delivery note, or the supplier’s reply. Upload a PDF or photo, or simply paste the text.</p><span className="step-chip">No new process to learn</span></article><article><div className="step-number">02 <Sparkles size={21}/></div><h3>Find the missing pieces.</h3><p>AI connects differently named items and points to the exact evidence. You review the finding before a claim is prepared.</p><span className="step-chip">Evidence you can inspect</span></article><article><div className="step-number">03 <CheckCheck size={21}/></div><h3>Close the loop.</h3><p>Prepare a clear claim. Match the credit note when it arrives. If only part was credited, the remainder stays open.</p><span className="step-chip">Every credit accounted for</span></article></div></section>
    <section id="why-remainder" className="why-section"><div><div className="eyebrow">SMALL AMOUNTS. REAL MARGINS.</div><h2>You run a business.<br/><em>Not a paper chase.</em></h2><p>A promise isn’t a credit. An alert isn’t a resolution.<br/>Remainder gives the little things a place to land—<br/>and a clear next step.</p><Link className="text-link" to="/signup">Make room for the work you love <MoveUpRight size={16}/></Link></div><div className="value-list"><article><ShieldCheck/><div><h3>Proof before confidence.</h3><p>Every claim links to the words in your documents. Ambiguity gets flagged, not filled in.</p></div></article><article><Link2/><div><h3>A memory for the details.</h3><p>Save supplier aliases and notes so tomorrow’s paperwork starts with what you know today.</p></div></article><article><CheckCheck/><div><h3>Useful from the first case.</h3><p>Download a claim and evidence pack. Your existing accounting system stays part of your workflow.</p></div></article></div></section>
    <section id="pricing" className="pricing-section"><div><div className="eyebrow">START SMALL. MAKE IT COUNT.</div><h2>Good for your books.<br/><em>Kind to your budget.</em></h2><p>The launch pilot is free. Our proposed paid plan is<br/>$29 per location, per month after the pilot.<br/>No billing is enabled during the pilot.</p></div><div className="price-card"><div className="price-tag">FOUNDING PILOT</div><h3>One location. Less loose ends.</h3><div className="price">Free <span>during the pilot</span></div><ul><li><Check/> Evidence-backed recovery cases</li><li><Check/> Partial credit tracking</li><li><Check/> Supplier memory & audit trail</li><li><Check/> PDF, CSV, email & data exports</li></ul><Link to="/signup" className="button">Create your workspace <ArrowRight size={16}/></Link><p>AI usage is limited by the configured provider allowance.</p></div></section>
    <section className="last-word"><img src="/favicon.svg" alt=""/><h2>Keep the relationship.<br/><em>Recover the remainder.</em></h2><button className="button button-large" onClick={onDemo} disabled={busy}>See it in action <ArrowRight size={18}/></button></section></main><footer className="landing-footer"><Logo small/><span>Built by Shivam Gupta · Evorozen Apex 2026</span><div><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><a href="https://github.com/shi1720/evorozen" target="_blank" rel="noreferrer">GitHub <MoveUpRight size={12}/></a></div></footer>
  </div>;
}
